// Guard for the project constraint: no em dashes anywhere in the files this
// system generates. The two operator provided CLA texts are out of scope: they
// are not created or edited here and are excluded below.

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

// The em dash is written as a Unicode escape (U+2014) so this guard file does
// not itself contain the character it searches for.
const EM_DASH = String.fromCodePoint(0x2014);
const REPO_ROOT = join(__dirname, '..');

// Directories generated by this build that should be free of em dashes. The
// signature data lives in the private store repository, not in this Action
// repository, so there is no data/ directory to scan here.
const SCANNED_DIRS = ['src', 'tests', 'scripts', 'config', '.github'];

// Individual root files generated by this build. This repository publishes a
// closed-contribution CONTRIBUTING.md; the operational CONTRIBUTIONS.md notice
// stays in the private store repository.
const SCANNED_ROOT_FILES = [
  'README.md',
  'PRIVACY.md',
  'CONTRIBUTING.md',
  'LICENSE',
  'action.yml',
  'package.json',
  'tsconfig.json',
  'eslint.config.mjs',
  '.gitignore',
];

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

function collectFiles(): string[] {
  const files: string[] = [];
  for (const dir of SCANNED_DIRS) {
    files.push(...walk(join(REPO_ROOT, dir)));
  }
  for (const file of SCANNED_ROOT_FILES) {
    files.push(join(REPO_ROOT, file));
  }
  return files;
}

describe('no em dashes in generated files', () => {
  it('contains no U+2014 em dash character', () => {
    const offenders: string[] = [];
    for (const file of collectFiles()) {
      const content = readFileSync(file, 'utf8');
      if (content.includes(EM_DASH)) {
        offenders.push(file);
      }
    }
    expect(offenders).toEqual([]);
  });
});
